### ISSUE TITLE
Неверная установка gettext

### ISSUE THREAD

**Issue by re15er** [Linux4Yourself/book#1001]
В разделе https://lx4u.ru/dev/build-temp-system/gettext/ после команды make DESTDIR=/usr install пакет устанавливается в /usr/usr/local вместо ожидаемого /usr/local

**Comment by makpif** [comment]
у configure отсутствует ключ --prefix=/usr

**Comment by makpif** [comment]
И зачем DESTDIR=/usr нужен??
