### ISSUE TITLE
Битая ссылка https://lx4u.ru/rel/stable/kernel/kernel-setup-intro/additional/LinuxStructure1

### ISSUE THREAD

**Issue by ElderlyLinuxUser** [Linux4Yourself/book#1015]
Ссылка https://lx4u.ru/rel/stable/kernel/kernel-setup-intro/additional/LinuxStructure1 битая, 404 Not Found

**Comment by makpif** [comment]
где эта ссылка находится?

**Comment by ElderlyLinuxUser** [comment]
Привет, извини, с работы не могу отвечать. Вечером, к моменту, когда 
добрался до дома, уже исправили.

makpif ***@***.***> 29 декабря 2021 г. 09:44:02 написал:
