### ISSUE TITLE
Автоматизация вноса изменений в файл `md5sums`

### ISSUE THREAD

**Issue by Linuxoid85** [Linux4Yourself/book#1050]
Очень часто как в этом файле, так и в `md5` из `packages.json` встречаются ошибки в контрольных суммах. Процесс внесения правок в эти файлы можно автоматизировать, тем самым сократив число ошибок. У меня есть один скрипт, выполняющий подобное, можно переделать его для руководства. Вопрос - действительно ли это требуется?

**Comment by makpif** [comment]
md5 и так автоматизированны

**Comment by Linuxoid85** [comment]
Да, я разобрался, поэтому и закрыл issue)
