### ISSUE TITLE
Зарегистрироваться на distrowatch

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/book#401]

**Comment by makpif** [comment]
я хз как это сделать

**Comment by Linuxoid85** [comment]
> я хз как это сделать

Регистрация [здесь](https://distrowatch.com/dwres.php?resource=submit)

Однако это нужно сделать после выхода первой версии книги. Она запланорована на 1 августа, судя по [milestone](https://github.com/Linux4Yourself/Linux4Yourself.Book/milestone/1). Хотя я думаю, что релиз выйдет чуть раньше. Судя по [этому](https://github.com/Linux4Yourself/Linux4Yourself.Book/projects/1). Добавить ещё пару каких-либо issue, плюс время на выполнение + исправление всех ошибок перед выходом релиза (как грамматических, так и всех остальных).

***
учитывая время ожидания регистрации на distro watch, уже вторая версия релизнется 😂️.

**Comment by avmaisak** [comment]
Примерно так и есть.

**Comment by avmaisak** [comment]
отправлена заявка по  email. Ждём результат

**Comment by rosti-il** [comment]
@avmaisak А под каким именем этот дистрибутив будет фигурировать в Distrowatch? Посмотрел сейчас **[список](https://distrowatch.com/dwres.php?resource=submit#waiting)** ожидающих подтверждения дистрибутивов и не нашёл. Ещё там написано, что за 220 долларов дистрибутив можно добавить сразу, без ожидания.

**Comment by avmaisak** [comment]
@rosti-il  - Заявка была отправлена. Ожидаем внесения в список на ожидание. Предполагаю, что время может сильно затянуться. Заявка была отправлена под названием Lx4u.

**Comment by avmaisak** [comment]
@rosti-il 
отправил повторно. Ожидаем под названием LX4U (Linux for yourself)

**Comment by avmaisak** [comment]
@rosti-il  - зарегистрировали. См. в списке на ожидание
