### ISSUE TITLE
Проверить наличие SBU для каждого пакета

### ISSUE THREAD

**Issue by Linuxoid85** [Linux4Yourself/book#593]
Не отображается SBU для пакета [Gettext](https://lx4u.ru/rel/1.0/#/build-system/gettext).

UPD 12.09. Так же желательно проверить на наличие всех sbu* в json.

**Comment by makpif** [comment]
не заполнено в json

**Comment by Linuxoid85** [comment]
В dev-ветке исправлено. Пока оставлю issue открытым, так как есть ещё некоторые пакеты, где не заполнено `sbu2` и `sbu` в json.

**Comment by makpif** [comment]
sbu (1) для темп системы должен быть, но я когда заполнял мог немного напутать в некоторых пакетах
