### ISSUE TITLE
Подсветка синтаксиса

### ISSUE THREAD

**Issue by Linuxoid85** [Linux4Yourself/book#616]
Было бы неплохим для всех внешних файлов сделать подсветку синтаксиса. Например, [здесь](https://lx4u.ru/rel/1.0/#/prepare/create-dirs) подсветка синтаксиса везде, кроме создания основных директорий. Такое разномордие никчему, ИМХО.

А вот [здесь](https://lx4u.ru/rel/1.0/#/prepare/download) помимо подсветки вообще дикость с командами `wget...`.

ИМХО, такая разрозненность оттолкнёт читателя.

**Comment by avmaisak** [comment]
в dev исправлено
