### ISSUE TITLE
Создать скрипт для генерации варианта без  packages

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/book#618]
скрипт который может сгенерировать версию заменив package-script  на команды из packges. И жедательно вставит шапку в мд. Полезно для генерации pdf или https://www.linux.org.ru/news/doc/16384915?cid=16391617

**Comment by avmaisak** [comment]
Тогда по идее, надо  пересматривать вариант docsify. И смотреть на что то иное. Хотя может SSR решить проблему. Буду думать

**Comment by makpif** [comment]
я думаю скрипт который просто извлекает из жсона команды схожим с package-script, копирует все мд в папку gen и заменяет package-script на извлеченные данные написать вполне реально. Возможно также и шапку обрабатывает. Ну для конвертации из docsify в pdf вроде есть программы

**Comment by avmaisak** [comment]
можно попробовать конечно...

**Comment by makpif** [comment]
#686

**Comment by makpif** [comment]
не актуально по мойму
