### ISSUE TITLE
Опечатки, глава "Сборка кросс компилятора".

### ISSUE THREAD

**Issue by aburuss** [Linux4Yourself/book#672]
1. https://lx4u.ru/rel/1.2/#/cross-toolchain/cross-toolchain

В названии главы - "Сборка кросс-компилятора" вместо "Сборка кросс компилятора".

2. https://lx4u.ru/rel/1.2/#/cross-toolchain/binutils. 

2.1. "Пакет содержит компоновщик, ассембл**ер, и др**угие утилиты и инструменты для работы с объектными файлам." заменить на "Пакет содержит компоновщик, ассембле**р и др**угие утилиты и инструменты для работы с объектными файлам."

2.2. Сокращение "MB" вместо "Mb" (если судить по Википедии).

2.3. Замечание по стилю:

https://lx4u.ru/rel/1.2/#/cross-toolchain/binutils?id=%D0%97%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2

Скорее всего нужно выбрать однообразное изложение пояснений команд и прочих действий и потом придерживаться его по всему тексту проекта. По ссылке - пояснения то с большой буквы, то с малой:

--with-sysroot=$LIN --target=$LIN_TGT - **необходимо** для кросс-компиляции.
--disable-nls - **Для** кросс-компилятора не требуется локализация.
 
2.4. https://lx4u.ru/rel/1.2/#/cross-toolchain/binutils?id=%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

По ссылке на дополнительную информацию о компиляции пакетов страница не найдена.

**Comment by makpif** [comment]
> 2.1. "Пакет содержит компоновщик, ассемблер, и другие утилиты и инструменты для работы с объектными файлам." заменить на "Пакет содержит компоновщик, ассемблер и другие утилиты и инструменты для работы с объектными файлам."

исправленно
