### ISSUE TITLE
Опечатки, глава "Заголовочные файлы ядра Linux"

### ISSUE THREAD

**Issue by aburuss** [Linux4Yourself/book#673]
1. https://lx4u.ru/rel/1.2/#/build-system/linux-headers?id=%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

Страница по ссылке на Glibc не найдена. В главе указана ссылка - https://lx4u.ru/rel/1.2/#/glibc , в документе есть ссылка - https://lx4u.ru/rel/1.2/#/build-temp-system/glibc , возможно, следует указать ее.

**Comment by makpif** [comment]
или https://lx4u.ru/rel/1.2/#/build-system/glibc я хз
