### ISSUE TITLE
Сделать нормальную локальную оффлайн версию книги

### ISSUE THREAD

**Issue by Linuxoid85** [Linux4Yourself/book#679]
Если клонировать себе на компьютер реп с книгой и выполнить `npm i;npm start`, то книга хоть и будет *локальной*, но без интернета её использовать не получится. Оттуда она тянет 90% команд (из репа Packages) и сам движок docsify.

**Comment by makpif** [comment]
вообще, по мойму реп packages - плохая идея. Особенно с учетом чейнджлога - приходиться все время комитить в 2 репа
Плюс этот баг. Я за то чтобы совместить репозитории packages и book в один (а возможно и scripts).

Речь не о содержимом, а только о репозиториях

**Comment by amadis** [comment]
наверное изначально имелось в виду - чтобы книгу полностью можно было скачать в виде pdf файла и ознакомиться/распечатать без подключения к инету...

**Comment by makpif** [comment]
нет, речь о том что npm start без инета не рабтает

**Comment by Linuxoid85** [comment]
https://github.com/Linux4Yourself/book/issues/778 - с этим будет работать хотя бы офлайн версия. А если вместе с изменениями заработает и SSR, то можно будет сгенерить и PDF- версию книги.

**Comment by makpif** [comment]
проверить как с mkdocs

**Comment by Linuxoid85** [comment]
Нормально без интернета пашет
