### ISSUE TITLE
Не указана переменная окружения CONFIG_SITE в скрипте .bashrc. Раздел Подготовительные работы, Настройка окружения

### ISSUE THREAD

**Issue by Mintormo** [Linux4Yourself/book#683]
![config_site_error](https://user-images.githubusercontent.com/2286710/124573838-91d0d900-de52-11eb-8bc7-48194f66dd57.png)

**Comment by makpif** [comment]
только вопрос - нужно ли оно?

**Comment by Mintormo** [comment]
> 
> 
> только вопрос - нужно ли оно?

Написано, что нужно для некоторых пакетов. Если не нужно, то надо бы тогда убрать упоминание в руководстве об этом.
