### ISSUE TITLE
Опечатка в дате changelog

### ISSUE THREAD

**Issue by Mintormo** [Linux4Yourself/book#684]
Страница с ошибкой: https://lx4u.ru/rel/1.2/#/prologue/changelog
![date_error](https://user-images.githubusercontent.com/2286710/124574429-22a7b480-de53-11eb-900d-d704690e72e6.png)

**Comment by Linuxoid85** [comment]
@avmaisak , я это уже исправил в dev же

**Comment by Linuxoid85** [comment]
UPD. Ан нет. У меня в клонированном репе на компе это есть, видать, не пушнул коммит с исправлением...

**Comment by avmaisak** [comment]
отказались от дат. В след. релизе неактульно
