### ISSUE TITLE
Опечатка в слове "понадобятся" в разделе про сборку пакета gettext. Раздел - Сборка временной системы

### ISSUE THREAD

**Issue by Mintormo** [Linux4Yourself/book#687]
Страница c ошибкой: https://lx4u.ru/rel/1.2/#/build-temp-system/gettext
![mistype](https://user-images.githubusercontent.com/2286710/124575779-5c2cef80-de54-11eb-86c8-14bda6bbf8b2.PNG)

**Comment by makpif** [comment]
и запятая перед "и"
