### ISSUE TITLE
не хватает точки

### ISSUE THREAD

**Issue by amadis** [Linux4Yourself/book#704]
![изображение](https://user-images.githubusercontent.com/3416446/124935645-80343080-e00e-11eb-871b-291198b00f5e.png)

**Comment by Linuxoid85** [comment]
Она ж здесь не нужна). Вы же не ставите точку после единиц `см`, `км`, `мм` и прочего.

**Comment by makpif** [comment]
оно не исправленно, там 2 предложения не разделены.
