### ISSUE TITLE
добавить информацию что команда на создание ссылки верная

### ISSUE THREAD

**Issue by amadis** [Linux4Yourself/book#706]
Наверное имеется в виду команда

`ln -sv $LIN/usr/lib32 $LIN/lib32`

Если да - исправьте, пожалуйста

![изображение](https://user-images.githubusercontent.com/3416446/124939184-942d6180-e011-11eb-959f-652d0c514d71.png)

**Comment by makpif** [comment]
все правильно. Иначе темп система хост сломает

**Comment by makpif** [comment]
вернее при входе в чрут симлинк не сработает

**Comment by avmaisak** [comment]
@makpif , @amadis  - я считаю, что если появились неоднозначности, то issue, не следует закрывать, а необходимо внести в текст уточнение, почему именно так .

**Comment by makpif** [comment]
надо в текст добавить предупреждение что команда верная
