### ISSUE TITLE
не отображается текст в параграфе "выход из среды chroot"

### ISSUE THREAD

**Issue by amadis** [Linux4Yourself/book#719]
см скрин:

![изображение](https://user-images.githubusercontent.com/3416446/125050573-bfb05a80-e0aa-11eb-9242-ff68833daa30.png)

**Comment by Linuxoid85** [comment]
![изображение](https://user-images.githubusercontent.com/71516578/125193518-6a647c80-e255-11eb-8ac8-afebf96fcaaf.png)

Пофикшено в dev-версии книги.
