### ISSUE TITLE
В пакете Acl указаны данные пакета Attr

### ISSUE THREAD

**Issue by Mintormo** [Linux4Yourself/book#728]
https://lx4u.ru/rel/1.2/#/build-system/acl

![err_acl](https://user-images.githubusercontent.com/2286710/125203123-dcea5200-e27f-11eb-82d8-9798f2873b59.PNG)

**Comment by Linuxoid85** [comment]
Мы знаем об этом баге, в dev-версии это пофикшено и отправится в версию 1.3.
