### ISSUE TITLE
Добавление информации о сборке пакета, используя раздельную структуру каталогов

### ISSUE THREAD

**Issue by Linuxoid85** [Linux4Yourself/book#779]
В ветке `classic-dirs` работаю над этим. Пока всё готово во временной системе, начал работать над базовой.

- [x] `acl`
- [x] `attr`
- [x] `bash` (готово в ВС)
- [x] `bzip2`
- [x] `coreutils`
- [x] `dbus`
- [x] `e2fsprogs`
- [x] `expect`
- [x] `eudev`
- [x] `file`
- [x] `findutils`
- [x] `gcc`
- [x] `glibc`
- [x] `grep`
- [x] `gzip`
- [x] `inetutils`
- [x] `kmod`
- [x] `libcap`
- [x] `libelf`
- [x] `man-db`
- [x] `ncurses`
- [x] `procps`
- [x] `psmisc`
- [x] `readline`
- [x] `sed`
- [x] `shadow`
- [x] `systemd`
- [x] `tar`
- [x] `util-linux`
- [x] `xz` (сделано в ВС)
- [x] `zlib`
- [x] `zstd`
- [x] `udev`

**Comment by avmaisak** [comment]
https://github.com/Linux4Yourself/book/issues/756
