### ISSUE TITLE
glibc • 2.34

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/book#802]

**Comment by makpif** [comment]
> Из-за расширения числа предоставляемых в glibc структур и функций не исключено появление проблем в приложениях, в которых наблюдается пересечение имён c ранее не использованными библиотеками libpthread, libdl, libutil, libresolv и libanl.

я читал чейнджлог, надо будет протестить, не заломало ли что нибудь

если что патч сделать не трудно

**Comment by makpif** [comment]
но пока стоит все равно обновить

**Comment by avmaisak** [comment]
https://wiki.linuxfromscratch.org/lfs/changeset/5a8d94fd357f3e5dd54e6ff183afce5271e372e7
