### ISSUE TITLE
docs/packages/core -> docs/packages

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/book#821]
раньше там было core и extra, но сейчас т.к. остался один core дополнительный уровень вложенности не нужен

**Comment by Linuxoid85** [comment]
Тогда придётся перелопачивать пол-книги)).

**Comment by makpif** [comment]
> Тогда придётся перелопачивать пол-книги)).

find -name *.md | xargs sed "s/packages\/core/packages/g"

**Comment by avmaisak** [comment]
ерунда )

**Comment by makpif** [comment]
> ерунда )

в ветке classic-dirs все на [filename :include] заменено, где путь стоит
