### ISSUE TITLE
fix glibc security issue

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/book#829]
https://wiki.linuxfromscratch.org/lfs/changeset/de8b6cb08abf05452b2e26dcc0329954bb98e822

```
sed -e '/NOTIFY_REMOVED)/s/)/ \&amp;\&amp; data.attr != NULL)/' \
-i sysdeps/unix/sysv/linux/mq_notify.c
```

**Comment by makpif** [comment]
зачем всех назначать?

**Comment by avmaisak** [comment]
@makpif чтобы пришло уведомление на всех, и принять решение, вносить ли это в проект

**Comment by makpif** [comment]
> @makpif чтобы пришло уведомление на всех, и принять решение, вносить ли это в проект

вносить конечно
