### ISSUE TITLE
Ссылка на дополнительную информацию информацию о FHS в дополнительных материалах ведет на 404 

### ISSUE THREAD

**Issue by keptelr** [Linux4Yourself/book#877]
Привет! 

Вспомогательные материалы -> Строение GNU/Linux. Часть 1. (https://lx4u.ru/rel/1.3/#/additional/LinuxStructure1)

Ссылка на другую информацию о FHS (https://lx4u.ru/rel/1.3/#/partition_catalogs) ведет в никуда.

**Comment by makpif** [comment]
должно видимо быть https://lx4u.ru/rel/1.3/#/additional/partitions_calalogs
