### ISSUE TITLE
Помощь в миграции на mkdocs

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/book#943]
### Discussed in https://github.com/Linux4Yourself/book/discussions/941

<div type='discussions-op-text'>

<sup>Originally posted by **Linuxoid85** October 29, 2021</sup>
Требуется помощь в замене всех `!>` и `?>` на:

Замена `?>`:

```
???+ note

    Текст
```

![Снимок экрана от 2021-10-29 17-48-44](https://user-images.githubusercontent.com/71516578/139455951-aa264853-2a30-405f-8274-5fe8e62d12ed.png)

Предупреждение:

```
???+ warning

    Текст
```

![Снимок экрана от 2021-10-29 17-49-19](https://user-images.githubusercontent.com/71516578/139456028-008c6e21-c0df-49a4-b3d6-f3220f4a2493.png)

> Возможно использование для пометок о проблемах в тестировании и прочем.

Опасность:
```
???+ danger

    Текст
```

![Снимок экрана от 2021-10-29 17-49-49](https://user-images.githubusercontent.com/71516578/139456109-48883fa5-2745-48a1-b52c-46595b6a05f2.png)

Баг:

```
???+ bug

    Текст
```

![Снимок экрана от 2021-10-29 17-50-18](https://user-images.githubusercontent.com/71516578/139456173-af1e2865-2288-488e-a3d6-1496f700fdf4.png)

Пример чего-л.:
```
???+ example

   Текст
```

![Снимок экрана от 2021-10-29 17-50-45](https://user-images.githubusercontent.com/71516578/139456245-a85d12da-b575-4041-aa11-27f32c10d867.png)

Полученные "блоки" можно скрыть (соответствующая кнопка в шапке). НО - с использованием `???+` они по умолчанию раскрыты, а с использованием `???` будет видна только шапка соответствующего цвета. Текст будет свёрнут.

Для получения доп. информации читайте [это](https://squidfunk.github.io/mkdocs-material/reference/admonitions/). В качестве примера смотрите [этот](https://github.com/Linux4Yourself/book/commit/b16a454d0c984532a4567ca502bcf69b8bf2c4ca) коммит.</div>

**Comment by Linuxoid85** [comment]
Надо бы сделать какие-то правила употребления определённых тегов. Например, сейчас `???+ warning` используется для предупреждений и пометок об ошибках тестирования. `???+ tip` используется для каких-то доп. сведений и пр.

**Comment by avmaisak** [comment]
актуализировал /mkdocs/prologue/typography/
