### ISSUE TITLE
Заменить все *.md в ссылках на *.html

### ISSUE THREAD

**Issue by Linuxoid85** [Linux4Yourself/book#969]
mkdocs, в отличие от docsify и других генераторов документации, не преобразовывает ссылки на md файлы. Поэтому получается примерно следующее:

![снимок8](https://user-images.githubusercontent.com/71516578/140652201-dcc8c54e-67cf-403f-a2fb-57f628ddb0ea.png)

**Comment by makpif** [comment]
можно просто убрать расширение
