### ISSUE TITLE
некорректная ссылка на страничке "Настройка zram"

### ISSUE THREAD

**Issue by amadis** [Linux4Yourself/book#978]
Вот текущая ссылка:
![изображение](https://user-images.githubusercontent.com/3416446/141132294-1d6fb5d2-8a71-4ffd-a78d-1c701b8de1ac.png)

Правильная же такая:
![изображение](https://user-images.githubusercontent.com/3416446/141132337-3cf0fb2e-3e4b-49aa-81bb-2669063a5853.png)

**Comment by Linuxoid85** [comment]
См. #979
