### ISSUE TITLE
некорректная ссылка на старничке "Выбор размера файла подкачки"

### ISSUE THREAD

**Issue by amadis** [Linux4Yourself/book#979]
![изображение](https://user-images.githubusercontent.com/3416446/141132869-276df723-c737-4b72-ad06-7972cee3484f.png)

**Comment by makpif** [comment]
наверно кто то ссылки через sed правил

**Comment by Linuxoid85** [comment]
Дело не в ссылках, а в том, что mkdocs неправильно создаёт ссылки. Либо нужно использовать абсолютный путь, либо указать, что файл находится на уровень выше.
