### ISSUE TITLE
После входа в окружение chroot недоступны команды

### ISSUE THREAD

**Issue by re15er** [Linux4Yourself/book#999]
С раздельной структурой каталогов после входа в окружение chroot недоступны команды: ln, cat, chmod, chgrp, touch, bash. Выполнение команд из раздела https://lx4u.ru/dev/build-temp-system/create-files/ завершаются ошибками. Указанные исполняемые файлы расположены в /bin, но при входе в chroot указана PATH=/usr/bin

**Comment by Linuxoid85** [comment]
О таком баше уже писал, выполните `export PATH=/bin:/sbin:/usr/bin:/usr/sbin`.
